name: Build Backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.repository == 'HowAboutThere/HowAboutThere-BE'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Verify Java version
        run: java -version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Backend with Gradle
        run: ./gradlew build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get image tag(version)
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: Build, tag, and push image to Amazon ECR
        id: image-info
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: how_about_there/server
          IMAGE_TAG: ${{ steps.image.outputs.version }}
        run: |
          echo "ecr_repository=$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v4.2.1
        with:
          repository: HowAboutThere/HowAboutThere-Gitops
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: infra

      - name: Substitute environment variables
        run: |
          export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          export AWS_REGION=ap-northeast-2
          cp infra/environment/k8s-manifest-repo/overlays/dev/kustomization.yaml infra/environment/k8s-manifest-repo/overlays/dev/kustomization.yaml.bak
          envsubst < infra/environment/k8s-manifest-repo/overlays/dev/kustomization.yaml.bak > infra/environment/k8s-manifest-repo/overlays/dev/kustomization.yaml

      - name: Update image tag using kustomize
        run: |
          echo ${{ steps.login-ecr.outputs.registry }}
          echo ${{ steps.image-info.outputs.ecr_repository }}
          echo ${{ steps.image-info.outputs.image_tag }}
          
          cd infra/environment/k8s-manifest-repo/overlays/dev
          
          # kustomize 명령어로 이미지 태그만 업데이트
          kustomize edit set image ${{ steps.login-ecr.outputs.registry}}/${{ steps.image-info.outputs.ecr_repository }}:${{ steps.image-info.outputs.image_tag }}
          
          # 결과 확인
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd infra
          git config --global user.email "jjang3a@gmail.com"
          git config --global user.name "HyunJunSon"
          git add infra/environment/k8s-manifest-repo/overlays/dev/kustomization.yaml
          git commit -am "Update image tag"
          git push -u origin main